### ISSUE TITLE
build error in 'logs/Python-2.7.18/make.log': 'SIGWINCH' undeclared

### ISSUE THREAD

**Issue by NikitaFeodonit** [niXman/mingw-builds#574]
I cannot compile with Python 2.7.18, I get a build error in logs/Python-2.7.18/make.log:

```
E:/Dev/projects/MinGW-builds/msys64/home/ilia/mingw-builds-my/src/Python-2.7.18/Modules/readline.c: In function 'readline_sigwinch_handler':
E:/Dev/projects/MinGW-builds/msys64/home/ilia/mingw-builds-my/src/Python-2.7.18/Modules/readline.c:837:17: error: 'SIGWINCH' undeclared (first use in this function); did you mean 'SIGINT'?
  837 |     PyOS_setsig(SIGWINCH, readline_sigwinch_handler);
      |                 ^~~~~~~~
      |                 SIGINT
E:/Dev/projects/MinGW-builds/msys64/home/ilia/mingw-builds-my/src/Python-2.7.18/Modules/readline.c:837:17: note: each undeclared identifier is reported only once for each function it appears in
E:/Dev/projects/MinGW-builds/msys64/home/ilia/mingw-builds-my/src/Python-2.7.18/Modules/readline.c: In function 'setup_readline':
E:/Dev/projects/MinGW-builds/msys64/home/ilia/mingw-builds-my/src/Python-2.7.18/Modules/readline.c:945:37: error: 'SIGWINCH' undeclared (first use in this function); did you mean 'SIGINT'?
  945 |     sigwinch_ohandler = PyOS_setsig(SIGWINCH, readline_sigwinch_handler);
      |                                     ^~~~~~~~
      |                                     SIGINT
```

My build script:
``` 
./build \
--buildroot=/home/ilia/mingw-builds-my \
--mode=gcc-11.2.0 \
--enable-languages=c,c++ \
--arch=x86_64 \
--exceptions=seh \
--threads=posix \
--rt-version=v9 \
--with-default-msvcrt=msvcrt \
--rev=1 \
--static-gcc \
--bin-compress \
--src-compress \
--jobs=4 
```

**Comment by NikitaFeodonit** [comment]
I use the latest mingw-builds from develop branch.

**Comment by niXman** [comment]
hi,

very strange... because the builds was successfully finished on github actions: https://github.com/niXman/mingw-builds/actions/runs/1415861367

**Comment by NikitaFeodonit** [comment]
I changed the root path from `E:/Dev/projects/MinGW-builds/msys64` to `E:/msys64` and deployed the MSYS2 and mingw-builds from scratch. All built successfully.

Maybe the length of the path had an impact.

I think this issue can be closed. Thanks.

**Comment by niXman** [comment]
> I think this issue can be closed.

then close it please.
