### ISSUE TITLE
Error when building gcc-5.5.0

### ISSUE THREAD

**Issue by eldiener** [niXman/mingw-builds#486]
When building with mode=gcc-5.5.0, whether with --arch=i686 or with --arch=x86_64, I get the error:

../../../../src/gcc-5.5.0/gcc/graphite-optimize-isl.c:30:10: fatal error: isl/band.h: No such file or directory
 #include <isl/band.h>
          ^~~~~~~~~~~~
compilation terminated.

When I look at graphite-optimize-isl.c I see:

```
#ifdef HAVE_isl
#include <isl/constraint.h>
#include <isl/set.h>
#include <isl/union_set.h>
#include <isl/map.h>
#include <isl/union_map.h>
#include <isl/schedule.h>
#include <isl/band.h>
#include <isl/aff.h>
#include <isl/options.h>
#endif
```
and indeed when looking at the source for isl-0.19 there is no band.h whereas all the other isl header files listed above do exist.

Is this just an error in the latest gcc-5.5.0 distribution ? It is not a big issue for me as I already have the mingw-w64 distribution for gcc-5.4.0, but I am wondering if you see what might be wrong here.

**Comment by niXman** [comment]
because gcc-5.5.0 uses another version of isl.

**Comment by Furniel** [comment]
Looks like i missed something. Isl 0.18 can be used for gcc 5.5. I need to recheck gcc 6x branch for isl version compability and after that i'll fix this bug

**Comment by eldiener** [comment]
Thanks for the fix. I can assert that building gcc-6.5 works with isl 0.19. I haven't tried to build gcc-6.1 to gcc-6.4 with isl 0.19, since those other releases were part of the mingw-w64-install releases and I did not need to build them for myself.

**Comment by eldiener** [comment]
I am still seeing a different error when building gcc-5.5.0. When --arch=i686 I am getting an error building gdb of:

```
../../../../src/gdb-8.3/gdb/cli/cli-script.c: In member function 'std::__cxx11::string user_args::insert_args(const char*) const':
../../../../src/gdb-8.3/gdb/cli/cli-script.c:862:16: error: 'to_string' is not a member of 'std'
    new_line += std::to_string (m_args.size ());
                ^
make[2]: *** [Makefile:1637: cli/cli-script.o] Error 1
```
but when I build with  --arch=x86_64 thje build is ssuccessful. Looking at the source file where the error is occurring we have the innocuous:

```
      if (p[4] == 'c')
	{
	  new_line += std::to_string (m_args.size ());
	  line = p + 5;
	}
```

Searching where 'to_string' exists in the standard library of the mingw32 compiler you are using to build I see it is in 'bits/basic_string.h' where it is defined within the preprocessor block of::

`#if __cplusplus >= 201103L && defined(_GLIBCXX_USE_C99)
`
The same line occurs for the compiler used when we have --arch=x86_64. So I am guessing that there is some reason why _GLIBCXX_USE_C99 is defined when --arch=x86_64 but not defined when  --arch=i686.  This is the only reason I can see why 'to_string' definitions are not found during the 32-bit compilation but are found during 64-bit compilations. I do not know where the configuration which defines or not defines _GLIBCXX_USE_C99 is made.

So while the issue is no longer 'isl', since 0.18 is being used instead of 0.19, this problem breaks the 32-bit compilation because the gdb package can not be built.

**Comment by Furniel** [comment]
@eldiener 
Hm, we can add -std=c++11 -D_GLIBCXX_USE_C99 flags to fix gdb 8.3 builds on old gcc versions, but i think than better way is to revevert gdb to 7.12 for gcc 4 and 5

**Comment by eldiener** [comment]
Thanks ! I will get the latest fix and test. I am curious though why gdb 8.3 for 5.5.0 failed for i686 while x86_64 succeeded. Does anybody know ?

**Comment by eldiener** [comment]
Both gcc-5.5.0 i686 and x86_64 built successfully with the latest fix. Thanks !

**Comment by niXman** [comment]
great!

close please.
